.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. deftchain_qt test_deftchain_qt
clean: FORCE
	$(MAKE) -C .. deftchain_qt_clean test_deftchain_qt_clean
check: FORCE
	$(MAKE) -C .. test_deftchain_qt_check
deftchain-qt deftchain-qt.exe: FORCE
	 $(MAKE) -C .. deftchain_qt
